### ISSUE TITLE
SoundCleod failed to connect to soundcloud.com

### ISSUE THREAD

**Issue by Scyther88** [salomvary/soundcleod#120] opened 2016-10-17 10:09 UTC
Open SoundCleod 1.1.0 application.
Get white window with text: "SoundCleod failed to connect to soundcloud.com :("
and a 'Try again' button. 

Was working until about 1 week ago.  

Attempts to fix:
0 Click 'Try again'
1 Tried reinstalling application
2 Used App Cleaner to remove Application Support, Caches, Saved State, BootCaches.
3 Tried re-downloading and reinstalling (steps 1, 2)
4 Disabled Little Snitch
5 Check Firewall off

All give same result as above.

6 Verified that Safari on the same Mac can connect to soundcloud.com - all functions OK.
7 Tried VOX - also connects and works fine.

iMac running MacOS Sierra 10.12.

**Comment by salomvary** [comment] 2016-10-18 06:30
Should be fixed in recently released [1.1.1](https://github.com/salomvary/soundcleod/releases/tag/v1.1.1). If the error screen still appears, please share the error code now shown below the error message.

**Comment by Scyther88** [comment] 2016-10-18 08:58
Thanks!  Same result with 1.1.1  :(  This is the error: ERR_INSECURE_RESPONSE

**Comment by salomvary** [comment] 2016-10-18 21:14
@Scyther88 I added some more detailed error logging in [1.1.2](https://github.com/salomvary/soundcleod/releases/tag/v1.1.2). To obtain and share the error logs for further clues, do the following:

- Make sure you have SoundCleod 1.1.2 installed under `/Applications`
- Start Terminal (`/Applications/Utilities/Terminal`)
- Copy `/Applications/SoundCleod.app/Contents/MacOS/SoundCleod` into the Terminal
- Hit Enter
- When SoundCleod has started and is showing the error screen with `ERR_INSECURE_RESPONSE` (or anything else) switch bach to Terminal
- Copy the error messages and add it to this GitHub issue

**Comment by Scyther88** [comment] 2016-10-19 11:34
autoUpdater checking for update
Certificate error on 'https://soundcloud.com/': net::ERR_CERT_REVOKED
Certificate data: {"issuerName":"GlobalSign Domain Validation CA - SHA256 - G2","subjectName":"*.soundcloud.com","serialNumber":"585CCA5B3FB340D214D78C7E","validStart":"Thu, 13 Oct 2016 17:57:04 GMT","validExpiry":"Wed, 09 May 2018 10:08:48 GMT","fingerprint":"sha256/v8JXwB6BMWm2RnYwAQnRwz1z0SeMJ+rViOgjYNSMKZ4="}
Failed to load 'https://soundcloud.com/' with ERR_INSECURE_RESPONSE
autoUpdater update not available

**Comment by salomvary** [comment] 2016-10-19 12:34
It definitely looks like some certificate caching issue on your end (possibly caused by the previous days certificate problems on soundcloud.com).

I'd recommend running through the recommended actions here (esp. the ones on globalsign.com):
http://status.soundcloud.com/day/2016/10/13

**Comment by Scyther88** [comment] 2016-10-20 11:51
Thanks that fixed it!

I was aware the certificate problem but assumed that since Safari was fine, so would SoundCleod.

I used the command from this [StackExchange forum](http://apple.stackexchange.com/questions/257080/how-to-tell-why-macos-thinks-that-a-certificate-is-revoked) which I trust more than GlobalSign (who didn't provide the correct command for Sierra initially).

Thanks again.

**Closed** 2016-10-20 11:52 UTC

**Comment by salomvary** [comment] 2016-10-20 11:54
Yay \o/
