### ISSUE TITLE
Every track listened to auto-liked/reposted

### ISSUE THREAD

**Issue by Baldrickk** [salomvary/soundcleod#163] opened 2018-02-04 12:05 UTC
SoundCleod on Windows 10

Every track that I listen to is being liked and reposted.  When I explore new music on SoundCloud, I don't know if I will like it or not.  I don't want tracks being automatically added to my collection of liked tracks whether I like them or not - I want my liked tracks to be the ones that I actually like.

There doesn't appear to be a setting to disable this.

**Comment by salomvary** [comment] 2018-02-04 13:23
Hello @Baldrickk,

Thas sounds real bad :( However I do not think the problem is caused by SoundCleod. You can try the following:
- Log in to [soundcloud.com](https://soundcloud.com) with the same account using a browser (like Chrome or Microsoft Edge) to see if whether this happens
- Go to the official [My account was hacked](https://help.soundcloud.com/hc/en-us/articles/115003450267-My-account-was-hacked) help page on soundcloud.com and follow the instructions
- If none of these help contact SoundCloud support

I hope this helps.

**Comment by salomvary** [comment] 2018-02-25 23:17
Fix landed in 1.3.3

**Closed by salomvary** 2018-02-25 23:17 UTC
