### ISSUE TITLE
Broken styles?

### ISSUE THREAD

**Issue by tyssen** [salomvary/soundcleod#100] opened 2016-03-23 23:18 UTC
I've opened Soundcleod today and there seems to be an issue with broken styling as you can see with the screenshot:

![screen shot 2016-03-24 at 9 14 44 am](https://cloud.githubusercontent.com/assets/370290/14003788/0a319726-f1a1-11e5-93aa-5a340afd4be1.png)

The Home and Collection links are now not clickable either. I'm running Soundcleod 0.18 on OSX 10.10.5.

**Comment by salomvary** [comment] 2016-03-24 13:46
Looks like a bug on soundcloud.com that affects Safari 8 too:
https://www.browserstack.com/screenshots/74c58c1163e0b89d435c83c452b9d6207db4432c

**Comment by salomvary** [comment] 2016-03-25 07:53
Confirmed to be due to dropped Safari 8 support on soundcloud.com (hopefully temporary). Unfortunately this is the same engine SoundCleod uses and there is no easy way to upgrade (at least on Yosemite or older).

Watch this space for updates.

**Comment by salomvary** [comment] 2016-03-29 13:15
And fixed on soundcloud.com.

**Closed by salomvary** 2016-03-29 13:15 UTC
