### ISSUE TITLE
Pause / play doesn't remember last position

### ISSUE THREAD

**Issue by kuba142** [salomvary/soundcleod#82] opened 2015-05-20 13:40 UTC
Only really noticed this when playing hour(+) long mixes but when pausing and resuming, playback starts back from an earlier time. 

I'm on OSX 10.10.3 using either the media keys or the pause / play button in app. Let me know if you need more information.

**Comment by accatyyc** [comment] 2015-05-20 14:22
I noticed this now as well. Seems like it's introduced in the latest version. I usually use SoundCleod for long mixes and I think I would've noticed it earlier if it existed.

For me it seems like it always jumps to the same (random) position in the mix if I pause and start playing again.

**Comment by salomvary** [comment] 2015-05-22 08:18
Invetigating. No success reproducing so far: 
- Start a long (about 1h) mix
- Seek to the middle & play
- Pause/resume works both with media keys, spacebar or buttons on the website

Perhaps the key to the problem is a longer mix? Or longer wait? Or longer playback before the pause?

Further details on this might help investigation (but I suspect it will be a problem on soundcloud.com rather than a bug introduced by SoundCleod).

SoundCleod and OSX versions could also be useful information.

**Comment by kuba142** [comment] 2015-05-22 11:43
Soundcleod version - 0.18; OSX 10.10.3

Doesn't seem to be an issue on the website. 

I think the steps to reproduce it would be
* start an hour long mix
* keep it playing for around 20 minutes (or any arbitrary time)
* pause, then resume
* listen for another x amount of time
* pause and resume which should potentially resume from the initial time you paused (~20 minute mark)

Seeking to times doesn't seem to have the issue.

Hope this helps and let me know if you need more info.

**Comment by salomvary** [comment] 2015-05-22 12:12
@kuba142 thanks, sounds helpful. Might be related to OSX, I'm on 10.9 (Mavericks) and don't see this happening.

**Comment by mikejimlarry** [comment] 2015-05-27 19:41
I am on Yosemite v10.10.3 with SoundCleod v0.18 and am having the same issue. Hour+ long mixes seem to always resume from pausing from wherever I paused the mix the first time.

**Comment by tyssen** [comment] 2015-07-22 01:47
> I am on Yosemite v10.10.3 with SoundCleod v0.18 and am having the same issue. Hour+ long mixes seem to always resume from pausing from wherever I paused the mix the first time.

Exactly the same set up and problem as me (except I'm on 10.10.4). A couple of times I've also had trouble dragging the slider to a later time, but mostly not.

**Comment by tyssen** [comment] 2015-07-22 02:45
Actually seems to be an issue only for short pauses. Just paused play for about half an hour and it started again from the correct spot, but if I only pause for a few seconds or minutes, then it goes back to the last 'good' pause point.

**Comment by kjoconnor** [comment] 2015-07-27 22:20
:+1:

**Comment by salomvary** [comment] 2016-09-30 10:24
Should be fixed in [1.0.0](https://github.com/salomvary/soundcleod/releases/tag/v1.0.0).

**Closed by salomvary** 2016-09-30 10:24 UTC
Labels: bug
